wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.2
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1632859010
    t:
      1:
      - 3
      2:
      - 3
      3:
      - 2
      4: 3.7.11
      5: 0.12.2
      8:
      - 5
batch_size:
  desc: null
  value: 4
epochs:
  desc: null
  value: 8
lr:
  desc: null
  value: 0.0038948896524957457
lr_multi:
  desc: null
  value: 0.27756878380198396
ranking_size:
  desc: null
  value: 26
rpi:
  desc: null
  value: 165
sampling_type:
  desc: null
  value: null
