wandb_version: 1

batch_size:
  value: 4
epochs:
  value: 8
lr:
  value: 0.0038948896524957457
lr_multi:
  value: 0.27756878380198396
ranking_size:
  value: 26
rpi:
  value: 165
sampling_type:
  value: null
